### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/1

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=Familiar

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "sql": "SELECT * FROM users", 
    "title": "Matrix",
    "year": 1999,
    "duration": 120,
    "genre": ["Accion"]
}

### Actualizar una pelicula con PATCH (actualizar solo una parte)
PATCH http://localhost:1234/movies/3
Content-Type: application/json

{
    "year": 1993
}